# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt
          #encode_as_base64: true
          #iterations: 1
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        api_user_provider:
          id: AppBundle\Security\User\ApiUserProvider

        database_users:
          entity: { class: AppBundle:User , property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            anonymous: ~
            http_basic:
              realm: "API: Please log in"
              provider: api_user_provider

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/api, roles: ROLE_API }
